[destination.filesystem]
bucket_url = "s3://bucket-name"

[destination.filesystem.credentials]
aws_access_key_id = "ACCESS_KEY" 
aws_secret_access_key = "SECRET_KEY" 

[destination.athena]
athena_work_group="WORKGROU-NAME"
aws_data_catalog="awsdatacatalog"
query_result_bucket="s3://RESULTS-BUCKET"

[destination.athena.credentials]
aws_access_key_id="ACCESS_KEY" 
aws_secret_access_key="SECRET_KEY" 
region_name="REGION" 